#!/bin/bash
# chkconfig: 2345 20 80
# description: SysV script for the iotnode service.
#   Node configuration will be retrieved from:
#   /etc/iotnode/config.json.
#
#   Logs will be written to:
#   /var/log/iotnode

# Source function library.
#. /etc/init.d/functions

start() {
    echo 'Starting IOT Node'
    pm2 --name iotnode start iotnode
}

stop() {
    echo 'Stopping IOT Node'
    pm2 stop iotnode
    pm2 delete iotnode
}

status() {
    pm2 show iotnode
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       status
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0 
